openapi: 3.0.0
info:
  title: logbook
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/users/{user_id}/logbooks/{logbook_id}':
    parameters:
      - type: string
        name: user_id
        in: path
        required: true
      - type: string
        name: logbook_id
        in: path
        required: true
    get:
      summary: logbook_id
      tags:
        - 3rd party
        - one touch
      responses: {}
components:
  schemas: {}
