openapi: 3.0.0
info:
  title: logbook
  version: '1.0'
  license:
    name: MIT
  description: Logbook API
  contact:
    name: seth
    url: gerou
    email: seth.gerou@noaa.gov
servers:
  - url: 'http://localhost:3000'
paths:
  '/logbooks/{logbook_id}':
    get:
      summary: logbook_id
      tags:
        - 3rd party
        - one touch
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/logbook-entry.v1.yaml
      description: get an existing logbook
      parameters: []
      operationId: showLogbookById
    parameters:
      - schema:
          type: number
        name: logbook_id
        in: path
        required: true
    put:
      summary: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/logbook-entry.v1.yaml
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./models/logbook-entry.v1.yaml
      description: update a logbook
      tags:
        - staff
        - 3rd party
      operationId: updateLogbook
  /logbooks:
    get:
      summary: getLogbooks
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./models/logbook-entry.v1.yaml
      description: get all logbooks
      operationId: getAllLogbooks
    post:
      summary: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/logbook-entry.v1.yaml
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./models/logbook-entry.v1.yaml
        description: ''
      description: submit a logbook
      operationId: submitALogbook
      tags:
        - 3rd party
        - one touch
components:
  schemas:
    Logbook Entry:
      type: array
      items:
        $ref: ./models/logbook-entry.v1.yaml
  securitySchemes: {}
