openapi: 3.0.0
info:
  title: logbook
  version: '1.0'
  license:
    name: MIT
  description: Logbook API
servers:
  - url: 'http://localhost:3000'
paths:
  '/logbooks/{logbook_id}':
    get:
      summary: logbook_id
      tags:
        - 3rd party
        - one touch
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/logbook-entry.v1.yaml
      description: get an existing logbook
      parameters: []
      requestBody:
        description: ''
      operationId: showLogbookById
    parameters:
      - schema:
          type: number
        name: logbook_id
        in: path
        required: true
components:
  schemas:
    Logbook Entry:
      type: array
      items:
        $ref: ./models/logbook-entry.v1.yaml
